### ISSUE TITLE
NBA-Data or SkullOwner problem. (Only my problem)

### ISSUE THREAD

**Issue by Bexr115** [filoghost/ChestCommands#61]
### What are you trying to do?
      Hello im trying to figure out how to add a head from Minecraft-heads.com to my ChestCommand (GUI).

### What have you tried so far?
I tried "NBA-Data" and "SkullOwner" like it is in the Wiki

### Platform
-Server version : 1.16.1 Spingot
-ChestCommand version : 3.3.1

### Additional context
I added a Screenshot from my last failed attempt.
![Download (8)](https://user-images.githubusercontent.com/70227681/91206335-4a909c80-e707-11ea-84e1-27d66ca0e099.png)

**Comment by filoghost** [comment]
The format changed between versions, I should add a disclaimer. This website lists the correct NBT for each version: https://minecraft-heads.com/custom-heads/blocks/40543-sand

**Comment by MrCyci6** [comment]
I have a similar problem, just I can't display the head since I am asked for the `MATERIAL:` function but when I put head / skull / head: 3 / skull: 3 it is not recognized

`test2:
  NBT-DATA: '{SkullOwner:{Id:"937fb91e-562d-4ab3-b495-3c8b183c38bb",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmFkYzA0OGE3Y2U3OGY3ZGFkNzJhMDdkYTI3ZDg1YzA5MTY4ODFlNTUyMmVlZWQxZTNkYWYyMTdhMzhjMWEifX19"}]}}}'
  MATERIAL: head:3
  NAME: '&6&lInformations'
  LORE:
    - '&7Pseudo : &6{player}'
    - '&7Argent : &c{money}'
    - 'test %luckperms_prefix%'
  POSITION-X: 1
  POSITION-Y: 1`
